name: gpu-tf
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - keras=2.6.0
  - albumentations=1.0.3
  - scikit-image=0.18.3
  - scikit-learn=1.0.1
  - py-opencv=4.5.3
  - tqdm=4.62.3
  - numpy=1.19.5
  - pandas=1.3.4
  - matplotlib=3.4.3
